#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: squadleader
  CLOUD_SQL_DATABASE_NAME: wormbin
  CLOUD_SQL_CONNECTION_NAME: wormbin-activity-monitor:us-west2:wormbin2



